name: ESP32 Filesystem Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_simulate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Wokwi simulation
      uses: wokwi/wokwi-ci-action@v1
      with:
        token: ${{ secrets.WOKWI_CLI_TOKEN }}
        path: .
        expect_text: 'System Started'
        timeout: 30000