name: ESP32 Test

on:
  push:
    branches:
      - main
      - feat/actions-build
  pull_request:
    branches:
      - main

jobs:
  wokwi_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install specific Wokwi CLI version
      run: |
        wget -q -O /usr/local/bin/wokwi-cli https://github.com/wokwi/wokwi-cli/releases/download/v0.25.0/wokwi-cli-linuxstatic-x64
        chmod +x /usr/local/bin/wokwi-cli
    
    - name: Test with Wokwi
      env:
        WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_API_KEY }}
      run: |
        wokwi-cli --timeout 10000 --expect-text "" .