name: ESP32 Test

on:
  push:
    branches:
      - main
      - feat/actions-build
  pull_request:
    branches:
      - main

jobs:
  wokwi_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Test with Wokwi
      uses: wokwi/wokwi-ci-action@v1
      with:
        token: ${{ secrets.WOKWI_API_KEY }}
        path: /
        expect_text: 'Smart Traffic Light - System Started'  # ou qualquer texto que seu código imprima